theme: jekyll-theme-minimal
title: Kevin Gallagher's Website
logo: /assets/img/face.png
author:
    name: Kevin Gallagher
    email: k.gallagher@fct.unl.pt

description: 
    This site serves as the personal page of Kevin Gallagher, an 
    Assistant Professor at Faculdade de Ciências e Tecnologia, Universidade 
    Nova de Lisboa.

publications: /publications
email: k.gallagher [at] fct.unl.pt
projects: /projects
teaching: /teaching
assignments: /assignments
docs: /docs
students: /students
