theme: jekyll-theme-minimal
title: Kevin Gallagher's Website
logo: /assets/img/face.png
author:
    name: Kevin Gallagher
    email: kevin.gallagher@tecnico.ulisboa.pt

description: 
    This site serves as the personal page of Kevin Gallagher, an Invited
    Assistant Professor at Instituto Superior Técnico, Universidade de Lisboa.

publications: /publications
email: kevin.gallagher [at] tecnico.ulisboa.pt
projects: /projects
teaching: /teaching
assignments: /assignments
